### ISSUE TITLE
Create a consumer for station data for exploration module from EDDN

### ISSUE THREAD

**Issue by Daniel-J-Mason** [eddb2-0/EDDB-2.0-backend#134]
Going to try and shrink down these issues.

We need to find a good message to consume from EDDN for most of our exploration station data. Currently we want to find a way to include landing pad size. Tie them to body data to feed landing pad size, planetary boolean, and arrival distance to trade module; as well as include fields we think are relevant to exploration.

**Comment by pveeckhout** [comment]
found the "Docked" message an ideal first candidate for the station data start in Exploration

started on mapping and processing it
