### ISSUE TITLE
Multiple containers failing health checks

### ISSUE THREAD

**Issue by TheGuyDanish** [eddb2-0/EDDB-2.0-backend#32]
Healthchecks on a fresh `docker compose up -d` run are failing on the message listener, REST, and processor containers. This is down to multiple factors.

1. Some software is not fully launching due to #31.
2. `curl` is not installed in the image the containers are built from, and as such, even if the software launched flawlessly, the healtcheck would fail.

I'd suggest adding curl with a `RUN apk add curl` step in the relevant Dockerfiles. 

cc @pveeckhout 
Related #27 #28 #31

**Comment by pveeckhout** [comment]
wil be fixed by using wget which is included in the image, so we don't need another build step and keep it as close to basic as possible
