### ISSUE TITLE
Whitelist for commodity homepage based on commodity name. 

### ISSUE THREAD

**Issue by Daniel-J-Mason** [eddb2-0/EDDB-2.0-backend#45]
Explanation:
If someone submits a nonexistent commodity, it will automatically publish to the commodity home page

Proposed Fix:
Simple whitelist to the known commodities.
This could either be done when collecting data or publishing to API, may be better for publishing as there is potential variability in naming from journals.

**Comment by jixxed** [comment]
additionally we can add automated reporting on newly found materials/commodities to a discord channel or something like it. optionally toggle on/off so it is only active with new releases of the game.

**Comment by pveeckhout** [comment]
I would suggest, for now, we still process all the commodities and store the data, but do not return the values if the names ar not in the whitelist
