### ISSUE TITLE
Kafka unable to find listeners

### ISSUE THREAD

**Issue by officialyinsane** [eddb2-0/EDDB-2.0-backend#59]
Kafka is non-functional when deployed to Morris.

The root cause here appears to be the configuration `KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092` set within the docker-compose.yml.

I have no doubt this worked properly when locally tested, however, when running on Morris, the container name is not "kafka" and therefore an UnknownHostException is seen repeatedly. Unfortunately this caused the disk to fill on Morris, and took out our Nexus instance.

For information, the container name on Morris is `edpn-kafka-1` and of course, the container name in Docker Networking, is the hostname by default. That said, it may not be the container name on other hosts, and should probably be an overridable configuration item (via .env file, etc).

Note: I'm also going to raise a separate issue for log rotation to be added

**Comment by pveeckhout** [comment]
very weird issue to be having.
![image](https://github.com/ed-pilots-network/backend/assets/1436380/93c602b5-2fd5-4eda-b07e-962e471ef034)
locally the container also gets added a number.

the network name for the container is the container name, so for all purposes, the config looks fine
